### PR TITLE
add support for logging in with 'regular-login'

### PR DESCRIPTION
**Pull request by antonmos**
This PR adds support for "regular authentication", which is in force when "basic authentication" is disabled.  This term is a bit odd, but trying to be consistent with wording on https://grafana.com/docs/grafana/latest/http_api/auth/#tokens

### CODE REVIEW

**Comment by antonmos** [comment]
Note, i couldnt not enter any phone number with numeric value above "16" into the CLA form :) I tried it in both Chrome and Firefox, even.

**Comment by lucassousaf** [comment]
Hey antonmos! Thank you very much for your contribution. It looks good. We would just like to request you to include the tests for the new methods, then we can merge the pull request. 

By the way, do you know if all the currently available methods are compatible with the new `regular-login`?

Thanks!

**Comment by antonmos** [comment]
> Hey antonmos! Thank you very much for your contribution. It looks good. We would just like to request you to include the tests for the new methods, then we can merge the pull request. 
> 
> 
> 
> By the way, do you know if all the currently available methods are compatible with the new `regular-login`?
> 
> 
> 
> Thanks!


Can you clarify what you mean by “all the currently available methods” ?
This change is backwards compatible and will default to basic-auth. Grafana also supports oauth but that is outside of the scope of the current pr.


Will add tests! Is there an easy way to run tests locally with the docket container used by Travis?

**Comment by lucassousaf** [comment]
Ok good, you answered my question.

Regarding the tests you can use the command in `.travis.yml` to run a Grafana container. You also need the following environment variables to be available:
* `GRAFANA_TEST_URI`
* `GRAFANA_TEST_USERNAME`
* `GRAFANA_TEST_PASSWORD`

They are used in the tests [here](https://github.com/magnetcoop/dashboard-manager.grafana/blob/master/test/magnet/dashboard_manager/grafana_test.clj#L11-L13) as part of the configuration.

**Comment by antonmos** [comment]
tests added. 
I took the liberty of refactoring the travis setup to make it easy to run the same tests as run in travis locally.  I would normally use a Makefile instead of adding shell scripts, but i didnt want to add another tool.  Let me know if you'd prefer that.

**Comment by asiergaldos** [comment]
Hi @antonmos - I've fixed the problem and you can sign the CLA.

**Comment by antonmos** [comment]
it is signed now.

**Comment by antonmos** [comment]
Thank you! I’ll start work on the dashboard creation now.

**Pull request merged**
